# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '1'
  Patch: '2'

steps:
- script: dotnet restore
  displayName: 'dotnet restore $(buildConfiguration)'

- script: dotnet build F3N.Hoard.Shared\F3N.Hoard.Shared.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet build F3N.Hoard.BlazorLocalStorage.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet build Hoard.Tests\Hoard.Tests.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --configuration $(buildConfiguration) --no-restore --verbosity normal --logger trx
  displayName: 'dotnet test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '394de134-869e-4730-9923-c11b476f2dcd'