name: .NET Core

on:
  push:
    branches: [ master, nuget-testing ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.201
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build Hoard
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test Hoard.Tests/Hoard.Tests.csproj --verbosity normal
      
    - name: Create NuGet Package F3N.Hoard
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack F3N.Hoard/F3N.Hoard.csproj --no-build --output .\ /p:PackageVersion=${{ env.GITHUB_REF_NAME }}
    - name: Create NuGet Package F3N.Hoard.BlazorServerStorage
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack F3N.Hoard.BlazorServerStorage/F3N.Hoard.BlazorServerStorage.csproj --no-build --output .\ /p:PackageVersion=${{ env.GITHUB_REF_NAME }}
    - name: Create NuGet Package F3N.Hoard.BlazorWasmStorage
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack F3N.Hoard.BlazorWasmStorage/F3N.Hoard.BlazorWasmStorage.csproj  --configuration Release --no-build --output .\ /p:PackageVersion=${{ env.GITHUB_REF_NAME }}
    - name: Create NuGet Package F3N.Hoard.Sqlite
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack F3N.Hoard.Sqlite/F3N.Hoard.Sqlite.csproj --no-build --output .\ /p:PackageVersion=${{ env.GITHUB_REF_NAME }}
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
