name: .NET Core

on:
  push:
    branches: [ master, nuget-test ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.201
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build Hoard
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test Hoard.Tests/Hoard.Tests.csproj --verbosity normal
      
    - name: Creating and publishing NuGet Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Packing version: ${{  github.ref_name }}"
        dotnet pack F3N.Hoard/F3N.Hoard.csproj --no-build --output .\ -p:PackageVersion=${{  github.ref_name }}
        dotnet pack F3N.Hoard.BlazorServerStorage/F3N.Hoard.BlazorServerStorage.csproj --no-build --output .\ -p:PackageVersion=${{  github.ref_name }}
        dotnet pack F3N.Hoard.BlazorWasmStorage/F3N.Hoard.BlazorWasmStorage.csproj  --configuration Release --no-build --output .\ -p:PackageVersion=${{  github.ref_name }}
        dotnet pack F3N.Hoard.Sqlite/F3N.Hoard.Sqlite.csproj --no-build --output .\ -p:PackageVersion=${{  github.ref_name }}
        # nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
