name: .NET Core

on:
  push:
    branches: [ master, nuget-testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Install dependencies (shared)
      run: dotnet restore F3N.Hoard.Shared
    - name: Build Hoard.Shared
      run: dotnet build F3N.Hoard.Shared --configuration Release --no-restore
    - name: Build Hoard
      run: dotnet build F3N.Hoard --configuration Release --no-restore
    - name: Build F3N.Hoard.BlazorLocalStorage
      run: dotnet build F3N.Hoard.BlazorLocalStorage --configuration Release --no-restore
    - name: Build Hoard.Tests
      run: dotnet build Hoard.Tests --configuration Release --no-restore
    - name: Test
      run: dotnet test Hoard.Tests/Hoard.Tests.csproj --verbosity normal
    - name: Create NuGet Package F3N.Hoard
      run: dotnet pack F3N.Hoard/F3N.Hoard.csproj --no-build --output .\ /p:PackageVersion=${{ env.PACKAGE_VERSION }}
    - name: Create NuGet Package F3N.Hoard.BlazorLocalStorage
      run: dotnet pack F3N.Hoard.BlazorLocalStorage/F3N.Hoard.BlazorLocalStorage.csproj --no-build --output .\ /p:PackageVersion=${{ env.PACKAGE_VERSION }}
    - name: Create NuGet Package F3N.Hoard.Sqlite
      run: dotnet pack F3N.Hoard.Sqlite/F3N.Hoard.Sqlite.csproj --no-build --output .\ /p:PackageVersion=${{ env.PACKAGE_VERSION }}
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: F3N.Hoard/F3N.Hoard.csproj
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: F3N.Hoard.BlazorLocalStorage/F3N.Hoard.BlazorLocalStorage.csproj
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}      
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: F3N.Hoard.Sqlite/F3N.Hoard.Sqlite.csproj
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}    
